apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: korrect-staging

resources:
  - ../base

nameSuffix: -staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api-staging.korrect.ng
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api-staging.korrect.ng
    target:
      kind: Ingress

images:
  - name: ghcr.io/korrect/gateway
    newTag: latest
  - name: ghcr.io/korrect/users
    newTag: latest
  - name: ghcr.io/korrect/artisan
    newTag: latest
  - name: ghcr.io/korrect/transaction
    newTag: latest
  - name: ghcr.io/korrect/messaging
    newTag: latest
  - name: ghcr.io/korrect/platform
    newTag: latest
