apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: korrect-production

resources:
  - ../base

nameSuffix: -production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
    target:
      kind: Deployment

images:
  - name: ghcr.io/korrect/gateway
    newTag: latest
  - name: ghcr.io/korrect/users
    newTag: latest
  - name: ghcr.io/korrect/artisan
    newTag: latest
  - name: ghcr.io/korrect/transaction
    newTag: latest
  - name: ghcr.io/korrect/messaging
    newTag: latest
  - name: ghcr.io/korrect/platform
    newTag: latest
