apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - gateway-deployment.yaml
  - users-deployment.yaml
  - artisan-deployment.yaml
  - transaction-deployment.yaml
  - messaging-deployment.yaml
  - platform-deployment.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: korrect
  app.kubernetes.io/managed-by: kustomize
