apiVersion: v1
kind: Service
metadata:
  name: korrect-gateway
  namespace: korrect
spec:
  selector:
    app: korrect-gateway
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: korrect-users
  namespace: korrect
spec:
  selector:
    app: korrect-users
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: korrect-artisan
  namespace: korrect
spec:
  selector:
    app: korrect-artisan
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: korrect-transaction
  namespace: korrect
spec:
  selector:
    app: korrect-transaction
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: korrect-messaging
  namespace: korrect
spec:
  selector:
    app: korrect-messaging
  ports:
    - port: 3004
      targetPort: 3004
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: korrect-platform
  namespace: korrect
spec:
  selector:
    app: korrect-platform
  ports:
    - port: 3005
      targetPort: 3005
  type: ClusterIP
